theme: jekyll-theme-minimal
title: Bioinformatics
description: This is my dedicated section on practical skills in bioinformatics, focusing on microbiome epidemiology and bacterial genomics. Here, you'll find detailed code examples to help you navigate various bioinformatics tools and process data using R.
